# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MAKEFILE                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mosakura <mosakura@student.42tokyo.jp>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/11/23 14:51:35 by mosakura          #+#    #+#              #
#    Updated: 2025/11/23 14:56:39 by mosakura         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		= client

SRCS		= ./printf/ft_printf.c \
				./printf/print.c \
				./printf/print.c \
				./printf/utils.c \

OBJS		= $(SRCS:.c=.o)

CC			= cc

FLAGS		= -Wall -Werror -Wextra -I ./

%.o: %.c
	$(CC) $(FLAGS) -c $< -o $@

$(NAME): $(OBJS)
	ar rc $(NAME) $(OBJS)

all: $(NAME)

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
